- Aplicacoes:
    - Musicas Igreja:
        href: https://musicas.networkmat.uk
        description: Gerenciamento de musicas da igreja
        icon: mdi-music
        server: local
        container: musicas-igreja-web
    - Gerenciamento Financeiro:
        href: https://financeiro.networkmat.uk
        description: Sistema financeiro
        icon: mdi-cash-multiple
        server: local
        container: gerenciamento-financeiro-web
    - Portfolio:
        href: https://resume.networkmat.uk
        description: Portfolio pessoal
        icon: mdi-briefcase
        server: local
        container: portfolio
    - Notes:
        href: https://notes.networkmat.uk
        description: Anotações pessoais
        icon: mdi-notebook-edit
        server: local
        container: notes

- Infraestrutura:
    - Dozzle:
        href: https://logs.networkmat.uk
        description: Logs Docker em tempo real
        icon: mdi-text-box-search
        server: local
        container: homelab-dozzle
    - Adminer:
        href: https://db.networkmat.uk
        description: Gerenciamento PostgreSQL
        icon: mdi-database
        server: local
        container: homelab-adminer
